### ISSUE TITLE
Nothing is there

### ISSUE THREAD

**Issue by ImpostorYT** [ToniMacaroni/ComputerInterface#42]
This might be because of the update but all lemming (don't tell me if I spelled that wrong) did was add a performance boost. Also, it shows the right keyboard but only in mountains.

**Comment by ItsJustLord** [comment]
The text for the mods keyboard are there, but no actual keys.

**Comment by ImpostorYT** [comment]
> The text for the mods keyboard are there, but no actual keys.
yes

**Comment by ImpostorYT** [comment]
update :000000000000000000000000000000000
