### ISSUE TITLE
Gorilla Tag Update Issue

### ISSUE THREAD

**Issue by ItsJustLord** [ToniMacaroni/ComputerInterface#43]
When the new Gorilla Tag update was released it broke the mod by replacing the Computer Interface screen with the normal computer screen. You cannot see the computer interface options only the normal options. Also the keyboard is replaced with the normal one. After awhile the text for the custom keys will come back, and the normal up and down keys are blacked out and non-useable. The big problem with this is that you cannot do ANYTHING using the computer. It does nothing and looks like you have everything selected (there is an arrow next to everything). Please fix this so I can continue using the mod and manage my other mods using this mod.

**Comment by designedsilence** [comment]
Yep same for me which is unforunate since I haven't tried any mods yet and seems almost all  of them are managed from the puter :D

**Comment by MrTeeYT** [comment]
Yeah same here hopefully it gets fixed soon

**Comment by gorillaman415** [comment]
SO SORRY GUYS! Just found out that you need utilis and banana computer to work, thanks to this discord u can get them!
https://discord.com/invite/shibamods
