### ISSUE TITLE
option 1 does not work

### ISSUE THREAD

**Issue by Destonary** [ToniMacaroni/ComputerInterface#46]
When I try to press option 1 it doesn't work, there is no vibration, and I do not leave the game.

**Comment by theboys780** [comment]
i've had this issue as well, when going into the game setting and trying to leave a room i cant and i cant join custom lobbies either

**Comment by DueHack12** [comment]
Option 1 isn't suppose to disconnect you in this mod, if you are in the command line, you have to do "leave"
