### ISSUE TITLE
Add the name filter to the command shell

### ISSUE THREAD

**Issue by EthanJamesBarron** [ToniMacaroni/ComputerInterface#59]
People are abusing the fact that you can set your name to bad stuff like KKK without the filter being enabled in the command shell. It's becoming a major problem. I joined the lobby mint and there were like 6 people spinning around in a cult with the n-word blatantly in their name

**Comment by developer9998** [comment]
i can try to add it to my computer interface fork later

**Comment by EthanJamesBarron** [comment]
@developer9998 Sure
