### ISSUE TITLE
all the keys around my hand get pushed down, it doesn't register it as pressing them but the visual effect of pressing them plays for all the keys around my hand

### ISSUE THREAD

**Issue by beanz00** [ToniMacaroni/ComputerInterface#82]
![20230507100051_1](https://user-images.githubusercontent.com/95457999/236648187-313ac888-0af3-4bcf-a82e-5dfcfaf55c4b.jpg)
i didnt push any keys in this photo, i just hovered my hand over the keyboard

**Comment by smegmaharcos** [comment]
I think it's the new update

**Comment by W74Fancy** [comment]
It IS the new update, they changed the hand collider to a bigger one for the ropes, that's why it does that
