### ISSUE TITLE
Interface has broken!

### ISSUE THREAD

**Issue by Goofert42** [ToniMacaroni/ComputerInterface#95]
The computer has no screen on it so it's just floating and I am unable to join lobbies using it. Any help or updates with this issue would be amazing! Thanks!

**Comment by SawyerISnotepic** [comment]
having the exact same issue but somehow it only appears in my left eye lol

**Comment by Kaydendro** [comment]
Yes, it shows the original computer from gorilla tag, but the words are there.  You can join any private codes and only one Lense can see the computer interface. And when you join a custom map, one Lense is completely black.
